import { useMemo } from 'react'
import katex from 'katex'

interface MathViewProps {
  latex: string
  // 'display' centres on its own line with larger glyphs; 'inline' flows in text.
  display?: boolean
  className?: string
}

// Renders a LaTeX string with KaTeX. `trust` is enabled so the \htmlClass macro
// used for redex highlighting is honoured; input is generated by our own pretty
// printer, never raw user text, so this is safe.
export default function MathView({ latex, display = false, className }: MathViewProps) {
  const html = useMemo(() => {
    try {
      return katex.renderToString(latex, {
        displayMode: display,
        throwOnError: false,
        trust: true,
        strict: false,
        output: 'html',
      })
    } catch {
      return `<span class="math-error">render error</span>`
    }
  }, [latex, display])

  return (
    <span
      className={className}
      // KaTeX output is trusted (we build the LaTeX ourselves).
      dangerouslySetInnerHTML={{ __html: html }}
    />
  )
}
